# Generated by Django 5.0.4 on 2024-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
